/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { CoinFlip__factory } from "./CoinFlip__factory";
export { CoinFlipAttack__factory } from "./CoinFlipAttack__factory";
