/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomiclabs/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "Attack",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Attack__factory>;
    getContractFactory(
      name: "CoinFlipAttack",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.CoinFlipAttack__factory>;
    getContractFactory(
      name: "CoinFlip",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.CoinFlip__factory>;
    getContractFactory(
      name: "Confidante",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Confidante__factory>;
    getContractFactory(
      name: "Attack",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Attack__factory>;
    getContractFactory(
      name: "EtherStore",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.EtherStore__factory>;
    getContractFactory(
      name: "Fallback",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Fallback__factory>;
    getContractFactory(
      name: "SimpleAttack",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SimpleAttack__factory>;

    getContractAt(
      name: "Attack",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Attack>;
    getContractAt(
      name: "CoinFlipAttack",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.CoinFlipAttack>;
    getContractAt(
      name: "CoinFlip",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.CoinFlip>;
    getContractAt(
      name: "Confidante",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Confidante>;
    getContractAt(
      name: "Attack",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Attack>;
    getContractAt(
      name: "EtherStore",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.EtherStore>;
    getContractAt(
      name: "Fallback",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Fallback>;
    getContractAt(
      name: "SimpleAttack",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.SimpleAttack>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.utils.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
  }
}
