/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as coinFlipAttackSol from "./CoinFlip-Attack.sol";
export type { coinFlipAttackSol };
import type * as etherStoreAttackSol from "./EtherStore-Attack.sol";
export type { etherStoreAttackSol };
import type * as simpleAttackSol from "./Simple-Attack.sol";
export type { simpleAttackSol };
export type { Attack } from "./Attack";
export type { CoinFlip } from "./CoinFlip";
export type { Confidante } from "./Confidante";
export type { EtherStore } from "./EtherStore";
export type { Fallback } from "./Fallback";
export * as factories from "./factories";
export { Attack__factory } from "./factories/Attack__factory";
export type { CoinFlipAttack } from "./CoinFlip-Attack.sol/CoinFlipAttack";
export { CoinFlipAttack__factory } from "./factories/CoinFlip-Attack.sol/CoinFlipAttack__factory";
export { CoinFlip__factory } from "./factories/CoinFlip__factory";
export { Confidante__factory } from "./factories/Confidante__factory";
export { EtherStore__factory } from "./factories/EtherStore__factory";
export { Fallback__factory } from "./factories/Fallback__factory";
export type { SimpleAttack } from "./Simple-Attack.sol/SimpleAttack";
export { SimpleAttack__factory } from "./factories/Simple-Attack.sol/SimpleAttack__factory";
